export const API_ERROR = "EVENT/API_ERROR_RECEIVED";
export const WEATHER_DATA_RECEIVED = "EVENT/WEATHER_DATA_RECEIVED";
export const METRIC_LIST_RECEIVED = "EVENT/METRIC_LIST_RECEIVED";
export const METRIC_CHART_SELECTED = "EVENT/METRIC_CHART_SELECTED";
